
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class frameMain extends javax.swing.JFrame {

    
    String item;
    /**
     * Creates new form frameMain
     */
    public frameMain() {
        initComponents();
        SetJam();
        SetTanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfItem = new javax.swing.JTextField();
        tfHarga_mkn = new javax.swing.JTextField();
        tfStruk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bSave = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        tfJml = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        wkt = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData1 = new javax.swing.JTable();
        bTotal = new javax.swing.JButton();
        bRefresh = new javax.swing.JButton();
        bDel = new javax.swing.JButton();
        bPrint1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        bMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("MS Mincho", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Restoran Mbak Min");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 230, 30);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 100);

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel3.setText("Pesanan");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3);
        jLabel3.setBounds(110, 0, 160, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(20, 20, 270, 30);

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel2.setText("lainnya)");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(20, 90, 180, 20);

        tfItem.setFont(new java.awt.Font("MS Mincho", 0, 12)); // NOI18N
        tfItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfItemActionPerformed(evt);
            }
        });
        jPanel4.add(tfItem);
        tfItem.setBounds(20, 110, 160, 30);

        tfHarga_mkn.setFont(new java.awt.Font("MS Mincho", 0, 12)); // NOI18N
        tfHarga_mkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHarga_mknActionPerformed(evt);
            }
        });
        jPanel4.add(tfHarga_mkn);
        tfHarga_mkn.setBounds(20, 230, 160, 30);

        tfStruk.setFont(new java.awt.Font("MS Mincho", 0, 12)); // NOI18N
        tfStruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStrukActionPerformed(evt);
            }
        });
        jPanel4.add(tfStruk);
        tfStruk.setBounds(20, 30, 160, 30);

        jLabel7.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel7.setText("No. Struk");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(20, 10, 80, 20);

        jLabel9.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel9.setText("Nama item (makanan/minuman/");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(20, 70, 230, 20);

        bSave.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        jPanel4.add(bSave);
        bSave.setBounds(20, 290, 90, 30);

        bClear.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        bClear.setText("Clear");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });
        jPanel4.add(bClear);
        bClear.setBounds(140, 290, 90, 30);

        tfJml.setFont(new java.awt.Font("MS Mincho", 0, 12)); // NOI18N
        tfJml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJmlActionPerformed(evt);
            }
        });
        jPanel4.add(tfJml);
        tfJml.setBounds(20, 170, 160, 30);

        jLabel5.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel5.setText("Jumlah Item");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(20, 150, 120, 20);

        jLabel6.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel6.setText("Harga Item");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(20, 210, 120, 20);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(20, 60, 270, 350);

        wkt.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        wkt.setText("Waktu");
        jPanel2.add(wkt);
        wkt.setBounds(330, 60, 100, 20);

        jLabel11.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel11.setText("Nama Kasir : Dhea");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(330, 20, 150, 20);

        tgl.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        tgl.setText("Tanggal");
        jPanel2.add(tgl);
        tgl.setBounds(330, 40, 100, 20);

        tableData1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No. Struk", "Nama Item", "JumlahItem", "HargaItem"
            }
        ));
        jScrollPane1.setViewportView(tableData1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(300, 90, 452, 150);

        bTotal.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        bTotal.setText("Total");
        bTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTotalActionPerformed(evt);
            }
        });
        jPanel2.add(bTotal);
        bTotal.setBounds(650, 270, 80, 30);

        bRefresh.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        bRefresh.setText("Refresh");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });
        jPanel2.add(bRefresh);
        bRefresh.setBounds(430, 270, 90, 30);

        bDel.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        bDel.setText("Delete");
        bDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelActionPerformed(evt);
            }
        });
        jPanel2.add(bDel);
        bDel.setBounds(320, 270, 80, 30);

        bPrint1.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        bPrint1.setText("Print");
        bPrint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrint1ActionPerformed(evt);
            }
        });
        jPanel2.add(bPrint1);
        bPrint1.setBounds(550, 270, 80, 30);

        jLabel4.setFont(new java.awt.Font("MS Mincho", 1, 14)); // NOI18N
        jLabel4.setText("Total Harga");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(320, 330, 100, 20);

        tfTotal.setFont(new java.awt.Font("MS Mincho", 0, 14)); // NOI18N
        jPanel2.add(tfTotal);
        tfTotal.setBounds(430, 320, 150, 40);

        bMenu.setText("Buka Menu");
        bMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenuActionPerformed(evt);
            }
        });
        jPanel2.add(bMenu);
        bMenu.setBounds(570, 20, 90, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 770, 430);

        setBounds(0, 0, 783, 568);
    }// </editor-fold>//GEN-END:initComponents

    private void tfItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfItemActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        //masuk ke menu makanan dan minuman
    }//GEN-LAST:event_jLabel3MouseClicked

    private void tfHarga_mknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHarga_mknActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHarga_mknActionPerformed

    private void tfJmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJmlActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        tfStruk.setText("");
        tfItem.setText("");
        tfJml.setText("");
        tfHarga_mkn.setText("");
        tfHarga_mkn.setText("");
    }//GEN-LAST:event_bClearActionPerformed

    private void bDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Anda yakin Menghapus Data!","",JOptionPane.YES_NO_OPTION);
        int baris = tableData1.getSelectedRow();
        if (konfirmasi ==0) {
  
        if (baris != -1) {
            String id = tableData1.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_restoran WHERE no_struk='"+tfStruk.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            
            if (status==1) {    
                JOptionPane.showMessageDialog(this,"Data Berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else {
                JOptionPane.showMessageDialog(this,"Data Gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Pilih Baris Data Terlebih Dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
        }
    }//GEN-LAST:event_bDelActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        if ("".equals(tfItem.getText()) || "".equals(tfJml.getText()) || "".equals(tfHarga_mkn.getText())) 
        {
            JOptionPane.showMessageDialog(this, "Data harus diisi","Error", JOptionPane.WARNING_MESSAGE);

        }else{
               int harga = Integer.parseInt(String.valueOf(tfHarga_mkn.getText()));
               int jml = Integer.parseInt(String.valueOf(tfJml.getText()));
               int total = harga*jml;
               
               tfHarga_mkn.setText(String.valueOf(total));
               
               
            }
        
//        int struk = 1;
    
            String SQL = "INSERT INTO tb_restoran(no_struk,nama_item,jumlah_item,harga_item)"+
            "VALUES('"+tfStruk.getText()+"','"+tfItem.getText()+"','"+tfJml.getText()+"','"+tfHarga_mkn.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this,"Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectdata();
            }
            else{
                JOptionPane.showMessageDialog(this,"Data gagal ditambahkan","Gagal",JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_bSaveActionPerformed

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        selectdata();
    }//GEN-LAST:event_bRefreshActionPerformed

    private void bTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTotalActionPerformed
        int jmlBaris = tableData1.getRowCount();
        int totalBiaya = 0;
        int jmlBarang, hargaBarang;
        TableModel tabelModel;
        tabelModel = tableData1.getModel();
        for (int i=0; i<jmlBaris; i++){
        jmlBarang = Integer.parseInt(tabelModel.getValueAt(i, 2).toString());
        hargaBarang = Integer.parseInt(tabelModel.getValueAt(i, 3).toString());
        totalBiaya = totalBiaya + (jmlBarang*hargaBarang);
        }
        if (totalBiaya > 200000) {
            int diskon = totalBiaya*10/100;
            tfTotal.setText(String.valueOf(totalBiaya-diskon));
        }else
            tfTotal.setText(String.valueOf(totalBiaya));
    }//GEN-LAST:event_bTotalActionPerformed

    private void bPrint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrint1ActionPerformed
        MessageFormat header = new MessageFormat ("Daftar Transaksi Patria Stationary");
        MessageFormat footer = new MessageFormat ("Page {0, number, integer}");
        try{
            tableData1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }catch(java.awt.print.PrinterException e)
                {
            System.err.format("Cannot Prnt %s%n", e.getMessage());
        }
    }//GEN-LAST:event_bPrint1ActionPerformed

    private void tfStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStrukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStrukActionPerformed

    private void bMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenuActionPerformed
        new Menu().show();
        this.dispose();
    }//GEN-LAST:event_bMenuActionPerformed

    private void selectdata() {
        String kolom[]={"No. Struk","Nama Item","JumlahItem","HargaItem"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);   
        String SQL = "SELECT * FROM tb_restoran";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String id = rs.getString(1);
                String item = rs.getString(2);
                String jumlah = rs.getString(3);
                String harga = rs.getString(4);
//                String total = rs.getString(5);
                    String data[] = {id,item,jumlah,harga};
                    dtm.addRow(data);
            }
        }   catch(SQLException ex){
                    Logger.getLogger(frameMain.class.getName()).log(Level.SEVERE,null, ex);
                    }
            tableData1.setModel(dtm); 
    }
    
    private void SetJam() {
         ActionListener taskPerformer = new ActionListener(){
        public void actionPerformed(ActionEvent evt){
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                
                
                Date dt = new Date();
                int vh = dt.getHours();
                int vm = dt.getMinutes();
                int vs = dt.getSeconds();
                
                if (vh<=9){
                    nol_jam = "0";
                } if (vm <= 9) {
                    nol_menit = "0";
                } if (vs <= 9){
                    nol_detik = "0";
                }
               
                
                String h = nol_jam + Integer.toString(vh);
                String m = nol_menit + Integer.toString(vm);
                String s = nol_detik + Integer.toString(vs);
                wkt.setText(h+":"+m+":"+s);
            }
    };

   new Timer(100, taskPerformer).start();
}

    private void SetTanggal() {
        java.util.Date now = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyy/MM/dd");
        tgl.setText(kal.format(now));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClear;
    private javax.swing.JButton bDel;
    private javax.swing.JButton bMenu;
    private javax.swing.JButton bPrint1;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bSave;
    private javax.swing.JButton bTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableData1;
    private javax.swing.JTextField tfHarga_mkn;
    private javax.swing.JTextField tfItem;
    private javax.swing.JTextField tfJml;
    private javax.swing.JTextField tfStruk;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JLabel tgl;
    private javax.swing.JLabel wkt;
    // End of variables declaration//GEN-END:variables

    
}
